### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cancelled'

### ISSUE THREAD

**Issue by exhuma** [exhuma/lost-tracker#31]
```
2016-05-04 23:10:00 ERROR    lost_tracker.main /var/www/lost.lu/www/env/lib/python2.7/site-packages/flask/app.py:log_exception:1423 Exception on /station/Grillposten/dashboard [GET]
Traceback (most recent call last):
  File "/var/www/lost.lu/www/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/lost.lu/www/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/lost.lu/www/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/lost.lu/www/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/lost.lu/www/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/lost.lu/www/env/lib/python2.7/site-packages/lost_tracker/blueprint/station.py", line 146, in dashboard
    result = loco.get_dashboard(station)
  File "/var/www/lost.lu/www/env/lib/python2.7/site-packages/lost_tracker/core.py", line 508, in get_dashboard
    if not state.group.cancelled]
AttributeError: 'NoneType' object has no attribute 'cancelled'
```

**Comment by exhuma** [comment]
This was fixed in commit bf1eb1daed34
